#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="php-fpm"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting php-fpm ${PHP_VERSION}"
silent s6-setuidgid nginx php-fpm -F;
