#!/usr/bin/with-contenv bash


### Set Defaults
  PHP_LOG_LEVEL=${PHP_LOG_LEVEL:-"notice"}
  PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-"128M"}
  PHP_TIMEOUT=${PHP_TIMEOUT:-"180"}
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-"2G"}

### Timezone Config
  echo 'date.timezone='`cat /etc/timezone` >> /etc/php5/conf.d/timezone.ini

### Debug Mode
  if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
  PHP_LOG_LEVEL=debug    
    echo '**** DEBUGGING MODE ACTIVATED: Sorry - This version of PHP5 does not include XDebug'
 fi

    
# Adjust PHP Runtime Variables
  sed -i -e "s/<PHP_LOG_LEVEL>/$PHP_LOG_LEVEL/g" /etc/php5/php-fpm.conf
  sed -i -e "s/<PHP_MEMORY_LIMIT>/$PHP_MEMORY_LIMIT/g" /etc/php5/php-fpm.conf
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/php5/php-fpm.conf

 if [ "$DEBUG_SMTP" = "TRUE" ] || [ "DEBUG_SMTP" = "true" ] || [ "DEBUG_MODE" = "true" ] || [ "DEBUG_MODE" = "TRUE" ];  then
    ENABLE_SMTP=FALSE
    echo 'sendmail_path="/usr/local/bin/mhsendmail"' > /etc/php5/conf.d/smtp.ini
 fi
 
### SMTP Config
  if [ "$ENABLE_SMTP" = "TRUE" ] || [ "$ENABLE_SMTP" = "true" ];  then
    echo 'sendmail_path="/usr/bin/msmtp -C /etc/msmtp -t "' > /etc/php5/conf.d/smtp.ini
  fi

  mkdir -p /www/logs/php-fpm
  chown -R nginx /www/logs/php-fpm

  mkdir -p /tmp/state
  touch /tmp/state/init-20-php-fpm
