#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/20-php-fpm ]; then
	### Start php-fpm
	mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/20-php-fpm
fi


echo ''
echo '** [nginx-php-fpm] Starting php-fpm..'
exec s6-setuidgid nginx php-fpm7 -F;
